// SPDX-License-Identifier: MIT OR Apache-2.0
import { PohApiError } from "./errors.js";
import type {
  AnonymousVoteRequest,
  AnonymousVoteResponse,
  AttachCommitmentResponse,
  GroupResponse,
  PohClientOptions,
  StatusResponse,
  VerifyPassportResponse,
} from "./types.js";

const DEFAULT_BASE_URL = "https://api.foundation-global.com";

/**
 * Thin TypeScript client for the Foundation Proof of Humanity API.
 *
 * @example
 * ```ts
 * const client = new PohClient("poh_live_abc123");
 * const result = await client.verifyPassport("att_9f3a2b1c", proof, pubSignals);
 * console.log(result.nullifier);
 * ```
 */
export class PohClient {
  private readonly apiKey: string;
  private readonly baseUrl: string;

  constructor(apiKey: string, options?: PohClientOptions) {
    this.apiKey = apiKey;
    this.baseUrl = (options?.baseUrl ?? DEFAULT_BASE_URL).replace(/\/+$/, "");
  }

  // -----------------------------------------------------------------------
  // Public methods
  // -----------------------------------------------------------------------

  /**
   * Verify an ePassport ZK proof and receive a nullifier with a trust tier.
   *
   * @param attestationId - Attestation identifier from the ePassport scan.
   * @param proof         - ZK proof object generated by the client.
   * @param pubSignals    - Public signals accompanying the proof.
   * @param userContextData - Optional client-side context (device info, locale, etc.).
   * @returns Nullifier, trust tier, and verification timestamp.
   */
  async verifyPassport(
    attestationId: string,
    proof: Record<string, unknown>,
    pubSignals: Record<string, unknown>,
    userContextData?: Record<string, unknown>,
  ): Promise<VerifyPassportResponse> {
    return this._fetch("POST", "/api/v1/poh/verify-passport", {
      attestation_id: attestationId,
      proof,
      pub_signals: pubSignals,
      ...(userContextData !== undefined && { userContextData }),
    });
  }

  /**
   * Bind a Semaphore identity commitment to a verified identity.
   * Requires a Bearer JWT obtained after passport verification.
   *
   * @param commitment  - Semaphore identity commitment (bigint as string).
   * @param bearerToken - Bearer JWT issued after ePassport verification.
   * @returns Success flag and the attached commitment.
   */
  async attachCommitment(
    commitment: string,
    bearerToken: string,
  ): Promise<AttachCommitmentResponse> {
    return this._fetch(
      "POST",
      "/api/v1/poh/attach-commitment",
      { commitment },
      { Authorization: `Bearer ${bearerToken}` },
    );
  }

  /**
   * Retrieve the Semaphore group: all commitments, member count, and Merkle root.
   */
  async getGroup(): Promise<GroupResponse> {
    return this._fetch("GET", "/api/v1/poh/group");
  }

  /**
   * Cast an anonymous on-chain vote using a Semaphore ZK proof.
   *
   * @param proposalId        - On-chain proposal identifier.
   * @param optionId          - Selected voting option.
   * @param proof             - Semaphore ZK proof.
   * @param nullifier         - Proof nullifier to prevent double-voting.
   * @param signal            - Signal broadcast with the proof.
   * @param externalNullifier - External nullifier scoped to the proposal.
   * @returns Success flag and Solana transaction signature.
   */
  async anonymousVote(
    proposalId: string,
    optionId: string,
    proof: Record<string, unknown>,
    nullifier: string,
    signal: string,
    externalNullifier: string,
  ): Promise<AnonymousVoteResponse> {
    const body: AnonymousVoteRequest = {
      proposalId,
      optionId,
      proof,
      nullifier,
      signal,
      externalNullifier,
    };
    return this._fetch("POST", "/api/v1/poh/anonymous-vote", body);
  }

  /**
   * Look up the verification status of a nullifier.
   *
   * @param nullifier - The nullifier to look up.
   * @returns Existence, proof type, trust tier, timestamp, and commitment status.
   */
  async getProofStatus(nullifier: string): Promise<StatusResponse> {
    return this._fetch(
      "GET",
      `/api/v1/poh/status/${encodeURIComponent(nullifier)}`,
    );
  }

  // -----------------------------------------------------------------------
  // Internal
  // -----------------------------------------------------------------------

  /** @internal */
  private async _fetch<T>(
    method: "GET" | "POST",
    path: string,
    body?: Record<string, unknown> | object,
    extraHeaders?: Record<string, string>,
  ): Promise<T> {
    const url = `${this.baseUrl}${path}`;

    const headers: Record<string, string> = {
      "X-PoH-API-Key": this.apiKey,
      ...extraHeaders,
    };

    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }

    const res = await fetch(url, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      let errorMsg = res.statusText;
      let errorCode = "unknown";
      try {
        const payload = (await res.json()) as { error?: string };
        if (payload.error) {
          errorMsg = payload.error;
          errorCode = payload.error;
        }
      } catch {
        // response body was not JSON — keep statusText
      }
      throw new PohApiError(res.status, errorCode, errorMsg);
    }

    return (await res.json()) as T;
  }
}
