//! Foundation — identity_commitments program.
//!
//! Anchors a 32-byte commitment hash (SHA-256 of canonical sealed proof-artifact
//! bytes, produced on-device in a secure element) to Solana. Writes nothing
//! identifying — only the hash, the slot timestamp, and a one-byte PDA bump.
//! The human→hash mapping lives in the operator's off-chain store; the on-chain
//! record is the non-repudiable proof-of-time anchor.
//!
//! Single instruction: `anchor_commitment(hash)`. The payer is a server-held
//! Solana keypair (clients hold none). Re-anchor of the same hash fails with the
//! runtime `AccountAlreadyInUse` error — the caller treats that as idempotent
//! success and reads the existing record.

use anchor_lang::prelude::*;

// Generated by `anchor build` on 2026-04-25. Keypair at
// target/deploy/identity_commitments-keypair.json (git-ignored; backed up
// separately). Must stay in sync with Anchor.toml [programs.devnet].
declare_id!("2eLQB1hoLv7nXvu1RYWFZw6eSkVjzUZEYeLDWpms1WkC");

#[program]
pub mod identity_commitments {
    use super::*;

    /// Anchor a commitment hash on-chain. Creates a PDA seeded by
    /// `[b"commitment", hash]` so the same hash can only be anchored once —
    /// deduplication is enforced by Solana's account model, not on-chain logic.
    pub fn anchor_commitment(
        ctx: Context<AnchorCommitment>,
        hash: [u8; 32],
    ) -> Result<()> {
        let record = &mut ctx.accounts.record;
        record.hash = hash;
        record.anchored_at = Clock::get()?.unix_timestamp;
        record.bump = ctx.bumps.record;
        Ok(())
    }
}

#[derive(Accounts)]
#[instruction(hash: [u8; 32])]
pub struct AnchorCommitment<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + CommitmentRecord::SIZE,
        seeds = [b"commitment", hash.as_ref()],
        bump,
    )]
    pub record: Account<'info, CommitmentRecord>,

    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: Program<'info, System>,
}

/// On-chain anchor record. 41 bytes of state + 8-byte discriminator.
#[account]
pub struct CommitmentRecord {
    /// SHA-256 of canonical sealed-artifact bytes produced in Secure Enclave.
    pub hash: [u8; 32],
    /// Unix timestamp of the anchoring slot (seconds). Set from `Clock`.
    pub anchored_at: i64,
    /// PDA bump byte. Cached so re-derivation is a single-op CPU check.
    pub bump: u8,
}

impl CommitmentRecord {
    pub const SIZE: usize = 32 + 8 + 1;
}
